title: Aditya Ranganathan
description: > # this means to ignore newlines until "baseurl:"
  This is CS 424 Spring '22
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Aditya Ranganathan # add your name
author-img: david-freeman.jpg # add your photo
about-author: Data Analyst. Traveller, Master Procrastinator # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: adi-r # add your Github handle
social-linkedin: linkedin.com/in/adiranga/ # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
